# Uncomment the next line to define a global platform for your project
  platform :ios, '13.4'

target 'StudyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudyApp
  pod 'SwiftLint','0.43.1'
end
